-- ============================================================================
-- College Events Portal - Phase 3: Events & Registration Enhancement
-- ============================================================================
-- This migration adds support for event listings, detailed views, and
-- user registration tracking with proper constraints and indexing.
--
-- Key changes:
-- 1. Add 'image_path' column to events table for event images
-- 2. Add 'status' column to registrations table
-- 3. Verify UNIQUE (profile_id, event_id) constraint exists
-- 4. Add composite indexes for efficient queries
-- ============================================================================

-- ============================================================================
-- STEP 1: Add image_path to events table (if not already present)
-- ============================================================================
-- Purpose: Store the path to event images in Supabase storage
-- This column allows events to have custom images displayed in listings and detail pages

ALTER TABLE events
ADD COLUMN IF NOT EXISTS image_path VARCHAR(500);

-- Add comment for clarity
COMMENT ON COLUMN events.image_path IS 'Path to event image stored in Supabase storage (storage bucket: event-images)';

-- ============================================================================
-- STEP 2: Add status column to registrations table
-- ============================================================================
-- Purpose: Track registration status (registered, waitlisted, cancelled, etc.)
-- Allows for future expansion to support waitlists and cancellations

ALTER TABLE registrations
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'registered';

-- Add constraint to ensure valid status values
-- (This is commented out to maintain flexibility; consider enabling when status values are finalized)
-- ALTER TABLE registrations
-- ADD CONSTRAINT check_registration_status 
-- CHECK (status IN ('registered', 'waitlisted', 'cancelled'));

-- Add comment for clarity
COMMENT ON COLUMN registrations.status IS 'Registration status: registered, waitlisted, cancelled, etc.';

-- ============================================================================
-- STEP 3: Verify and document UNIQUE constraint
-- ============================================================================
-- The UNIQUE (profile_id, event_id) constraint prevents duplicate registrations
-- This constraint was created in migration 001_init.sql
-- 
-- Verify it exists with this query:
-- SELECT constraint_name
-- FROM information_schema.table_constraints
-- WHERE table_name = 'registrations' AND constraint_type = 'UNIQUE';
--
-- Expected output: A constraint named something like:
--   - registrations_profile_id_event_id_key (auto-generated by PostgreSQL)
--
-- Documentation:
-- - This constraint ensures each user can only register once per event
-- - If duplicate registration is attempted, PostgreSQL will raise:
--   ERROR: duplicate key value violates unique constraint "registrations_profile_id_event_id_key"
--
-- If constraint is missing for some reason, uncomment and run:
-- ALTER TABLE registrations
-- ADD CONSTRAINT unique_user_event_registration UNIQUE (profile_id, event_id);

-- ============================================================================
-- STEP 4: Create composite index for efficient registration queries
-- ============================================================================
-- Purpose: Speed up queries filtering registrations by event and profile
-- This index is used in checks like:
--   SELECT * FROM registrations WHERE event_id = ? AND profile_id = ?

CREATE INDEX IF NOT EXISTS idx_registrations_event_profile 
ON registrations(event_id, profile_id);

-- ============================================================================
-- STEP 5: Create index for listing user's registrations by status
-- ============================================================================
-- Purpose: Optimize queries for "show me all my registrations"

CREATE INDEX IF NOT EXISTS idx_registrations_profile_status 
ON registrations(profile_id, status);

-- ============================================================================
-- STEP 6: Create index for listing event registrations by status
-- ============================================================================
-- Purpose: Optimize queries for "show me all registrations for this event"

CREATE INDEX IF NOT EXISTS idx_registrations_event_status 
ON registrations(event_id, status);

-- ============================================================================
-- STEP 7: Create index on events.image_path for nullable column queries
-- ============================================================================
-- Purpose: Optimize queries that filter by presence of image
-- Useful for: "Show events with images" type queries

CREATE INDEX IF NOT EXISTS idx_events_image_path 
ON events(image_path) WHERE image_path IS NOT NULL;

-- ============================================================================
-- STEP 8: Document RLS Policies for Phase 3
-- ============================================================================
-- The following RLS policies should be created in Supabase dashboard
-- These ensure proper data access control for the registration system

-- Policy 1: Users can see all upcoming events (PUBLIC READ)
-- CREATE POLICY "events_select_public" ON events
-- FOR SELECT USING (true);

-- Policy 2: Organizers can create events (INSERT)
-- CREATE POLICY "events_insert_organizer" ON events
-- FOR INSERT WITH CHECK (
--   auth.uid()::text = organizer_id::text
--   AND (SELECT role FROM profiles WHERE id = auth.uid()::uuid) IN ('organizer', 'admin')
-- );

-- Policy 3: Organizers can update their own events (UPDATE)
-- CREATE POLICY "events_update_own" ON events
-- FOR UPDATE USING (auth.uid()::text = organizer_id::text)
-- WITH CHECK (auth.uid()::text = organizer_id::text);

-- Policy 4: Authenticated users can register for events (INSERT)
-- CREATE POLICY "registrations_insert_auth" ON registrations
-- FOR INSERT WITH CHECK (
--   auth.uid()::text = profile_id::text
-- );

-- Policy 5: Users can view their own registrations (SELECT)
-- CREATE POLICY "registrations_select_own" ON registrations
-- FOR SELECT USING (auth.uid()::text = profile_id::text);

-- Policy 6: Organizers can view registrations for their events (SELECT)
-- CREATE POLICY "registrations_select_organizer_events" ON registrations
-- FOR SELECT USING (
--   EXISTS (
--     SELECT 1 FROM events 
--     WHERE events.id = registrations.event_id 
--     AND events.organizer_id = auth.uid()::uuid
--   )
-- );

-- Policy 7: Users can cancel their own registrations (DELETE)
-- CREATE POLICY "registrations_delete_own" ON registrations
-- FOR DELETE USING (auth.uid()::text = profile_id::text);

-- ============================================================================
-- STEP 9: Enable RLS if not already enabled
-- ============================================================================
-- Uncomment these lines in Supabase SQL editor when ready to enable RLS:
--
-- ALTER TABLE events ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
--
-- Important: Test your policies thoroughly before enabling RLS in production
-- RLS can break queries if policies are not correctly configured

-- ============================================================================
-- STEP 10: Verify migration success
-- ============================================================================
-- Run these queries to verify all changes were applied:

-- 1. Check image_path column exists:
-- SELECT column_name, data_type FROM information_schema.columns 
-- WHERE table_name = 'events' AND column_name = 'image_path';

-- 2. Check status column exists in registrations:
-- SELECT column_name, data_type FROM information_schema.columns 
-- WHERE table_name = 'registrations' AND column_name = 'status';

-- 3. Check UNIQUE constraint exists:
-- SELECT constraint_name FROM information_schema.table_constraints
-- WHERE table_name = 'registrations' AND constraint_type = 'UNIQUE';

-- 4. Check new indexes:
-- SELECT indexname FROM pg_indexes 
-- WHERE tablename IN ('registrations', 'events') 
-- AND indexname LIKE 'idx_%';

-- ============================================================================